version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=rinhasenha
      - DEBUG=true
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    container_name: "mysql_1_F"
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=rinhasenha
      - MYSQL_DATABASE=rinha
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"