version: '3.5'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rinha
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=rinhasenha
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: "mysql:8.0"
    networks:
      - rinha
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rinhasenha
      - MYSQL_DATABASE=rinha
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

networks:
  rinha:
    driver: bridge