version: '3.5'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=rinhasenha
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    hostname: db
    ports:
      - "3307:3307"
    environment:
      - DB_HOSTNAME=db
      - MYSQL_ROOT_PASSWORD=rinhasenha
      - MYSQL_DATABASE=rinha
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1